### ISSUE TITLE
What would it take to support aarch64 (eg. M1/M2 CPUs)?

### ISSUE THREAD

**Issue by abailly** [hshq/harelang-harec#1]
I noticed there's not `rt/+Darwin/aarch64.s`, I would be interested in having hare working on this architecture but I have no idea where to start to provide those bindings.

**Comment by gaetgu** [comment]
Hi @abailly! I'm not affiliated with this project in any way, but I thought I'd chime in since I have some relevant information. 

About a year ago, I was working on porting `harec` to aarch64 (https://git.sr.ht/~gaetgu/hare-macOS), but I was pretty inexperienced in a lot of ARM stuff. Eventually I upgraded to macOS 13 (and now I'm on 14), which broke more stuff and I gave up.

That being said, I have recently regained interest in porting `harec` to Apple Silicon, which is why I saw your comment. If you or anyone else is interested in collaborating with me to get this done, please email me at  gabriel.ethan@gmail.com

**Comment by abailly** [comment]
I am definitely interested, but this will be a learning journey for me as my experience doing such low-level programming, esp.  on ARM, is basically 0 :) Let's see where we can go!

**Comment by hshq** [comment]
The following English comes from software translation:

Sorry, I am unable to provide assistance in this regard as I am completely unfamiliar with aarch64.
In fact, I don't have any low-level programming experience either, I just self-studied a little x86 assembly.
I did this to learn about Harelang, but I only have one Intel MBP on hand.
At the beginning, it was based on freebsd's x86 code modification, and I invested a lot of time searching for information online and debugging code.
I think it may be helpful to compare the differences between it and the original code repository, as well as the differences between RT/+Darwin and RT/+freebsd.

-----------------------------------------------------------------------------------------------

不好意思，我无法提供这方面的帮助，因为我完全不了解 aarch64 。
事实上，我也没有底层编程经验，只是自学过一点点 x86 汇编。
做这件事情是想了解 harelang ，但手头只有一台 intel mbp 。
刚开始是基于 freebsd 的 x86 代码修改的，投入了大量时间在网上查找资料和调试代码。
我想，比较它与原始代码仓库差异以及 rt/+darwin 和 rt/+freebsd 之间的差异可能会有帮助。

**Comment by hshq** [comment]
AArch64 support has been added and passed testing on the 2023 Mac mini.

已经加上了 aarch64 支持，在 2023 mac mini 上测试通过。
